In [1]:
import pandas as pd

# loading game_events.csv
df = pd.read_csv('kaggle raw data/game_events.csv')

# checking basic info
print(df.shape)
df.head()

(1035043, 10)

,game_event_id,date,game_id,minute,type,club_id,player_id,description,player_in_id,player_assist_id
0,2f41da30c471492e7d4a984951671677,2012-08-05,2211607,77,Cards,610,4425,"1. Yellow card , Mass confrontation",NaN,NaN
1,a72f7186d132775f234d3e2f7bc0ed5b,2012-08-05,2211607,77,Cards,383,33210,"1. Yellow card , Mass confrontation",NaN,NaN
2,b2d721eaed4692a5c59a92323689ef18,2012-08-05,2211607,3,Goals,383,36500,", Header, 1. Tournament Goal Assist: , Corner,...",NaN,56416.0
3,aef768899cedac0c9a650980219075a2,2012-08-05,2211607,53,Goals,383,36500,", Right-footed shot, 2. Tournament Goal Assist...",NaN,146258.0
4,5d6d9533023057b6619ecd145a038bbe,2012-08-05,2211607,74,Substitutions,383,36500,", Not reported",49499.0,NaN

In [2]:
df['date'] = pd.to_datetime(df['date'], errors='coerce')

In [3]:
df['description'] = df['description'].astype(str).str.strip().str.lstrip(',').str.strip()

In [4]:
df['player_in_id'] = df['player_in_id'].fillna(-1).astype(int)
df['player_assist_id'] = df['player_assist_id'].fillna(-1).astype(int)

In [5]:
df['minute'] = pd.to_numeric(df['minute'], errors='coerce').fillna(-1)

In [6]:
df['type'] = df['type'].str.strip().str.title()

In [7]:
df.drop_duplicates(inplace=True)

In [8]:
df['is_goal'] = df['type'] == 'Goals'
df['is_card'] = df['type'] == 'Cards'
df['is_substitution'] = df['type'] == 'Substitutions'

In [9]:
df['minute_bucket'] = pd.cut(df['minute'], bins=[-1, 15, 30, 45, 60, 75, 90, 120],
                             labels=['0–15', '16–30', '31–45', '46–60', '61–75', '76–90', '90+'])

In [10]:
df['has_assist'] = df['player_assist_id'] != -1

In [11]:
df['card_type'] = df['description'].apply(
    lambda x: 'Yellow' if 'Yellow' in x else 'Red' if 'Red' in x else 'Unknown'
)

In [12]:
df['is_header'] = df['description'].str.contains('Header', case=False, na=False)
df['is_own_goal'] = df['description'].str.contains('Own Goal', case=False, na=False)

In [13]:
print(df.dtypes)

game_event_id               object
date                datetime64[ns]
game_id                      int64
minute                       int64
type                        object
club_id                      int64
player_id                    int64
description                 object
player_in_id                 int64
player_assist_id             int64
is_goal                       bool
is_card                       bool
is_substitution               bool
minute_bucket             category
has_assist                    bool
card_type                   object
is_header                     bool
is_own_goal                   bool
dtype: object

In [14]:
print(df['minute_bucket'].value_counts())
print(df['has_assist'].value_counts())

minute_bucket
76–90    342642
61–75    278109
46–60    174165
31–45     99992
16–30     69390
0–15      44731
90+       10885
Name: count, dtype: int64
has_assist
False    878284
True     156759
Name: count, dtype: int64

In [15]:
df.head()

,game_event_id,date,game_id,minute,type,club_id,player_id,description,player_in_id,player_assist_id,is_goal,is_card,is_substitution,minute_bucket,has_assist,card_type,is_header,is_own_goal
0,2f41da30c471492e7d4a984951671677,2012-08-05,2211607,77,Cards,610,4425,"1. Yellow card , Mass confrontation",-1,-1,False,True,False,76–90,False,Yellow,False,False
1,a72f7186d132775f234d3e2f7bc0ed5b,2012-08-05,2211607,77,Cards,383,33210,"1. Yellow card , Mass confrontation",-1,-1,False,True,False,76–90,False,Yellow,False,False
2,b2d721eaed4692a5c59a92323689ef18,2012-08-05,2211607,3,Goals,383,36500,"Header, 1. Tournament Goal Assist: , Corner, 1...",-1,56416,True,False,False,0–15,True,Unknown,True,False
3,aef768899cedac0c9a650980219075a2,2012-08-05,2211607,53,Goals,383,36500,"Right-footed shot, 2. Tournament Goal Assist: ...",-1,146258,True,False,False,46–60,True,Unknown,False,False
4,5d6d9533023057b6619ecd145a038bbe,2012-08-05,2211607,74,Substitutions,383,36500,Not reported,49499,-1,False,False,True,61–75,False,Unknown,False,False

In [18]:
import numpy as np

df['player_in_id'] = df['player_in_id'].replace(-1, np.nan)
df['player_assist_id'] = df['player_assist_id'].replace(-1, np.nan)
df['minute'] = df['minute'].replace(-1, np.nan)

In [19]:
df.head()

,game_event_id,date,game_id,minute,type,club_id,player_id,description,player_in_id,player_assist_id,is_goal,is_card,is_substitution,minute_bucket,has_assist,card_type,is_header,is_own_goal
0,2f41da30c471492e7d4a984951671677,2012-08-05,2211607,77.0,Cards,610,4425,"1. Yellow card , Mass confrontation",NaN,NaN,False,True,False,76–90,False,Yellow,False,False
1,a72f7186d132775f234d3e2f7bc0ed5b,2012-08-05,2211607,77.0,Cards,383,33210,"1. Yellow card , Mass confrontation",NaN,NaN,False,True,False,76–90,False,Yellow,False,False
2,b2d721eaed4692a5c59a92323689ef18,2012-08-05,2211607,3.0,Goals,383,36500,"Header, 1. Tournament Goal Assist: , Corner, 1...",NaN,56416.0,True,False,False,0–15,True,Unknown,True,False
3,aef768899cedac0c9a650980219075a2,2012-08-05,2211607,53.0,Goals,383,36500,"Right-footed shot, 2. Tournament Goal Assist: ...",NaN,146258.0,True,False,False,46–60,True,Unknown,False,False
4,5d6d9533023057b6619ecd145a038bbe,2012-08-05,2211607,74.0,Substitutions,383,36500,Not reported,49499.0,NaN,False,False,True,61–75,False,Unknown,False,False

In [20]:
df.to_csv('cleaned_game_events.csv', index=False)